services:
    form.type.base_form:
        class: Jasny\FrameworkBundle\Form\BaseFormType
        tags:
            - { name: form.type, alias: base_form }
    form.type.field:
        class: Jasny\FrameworkBundle\Form\Type\FieldType
        tags:
            - { name: form.type, alias: field }
    form.type.date:
        class: Jasny\FrameworkBundle\Form\Type\DateType
        tags:
            - { name: form.type, alias: date }
    form.type.datetime:
        class: Jasny\FrameworkBundle\Form\Type\DateTimeType
        tags:
            - { name: form.type, alias: datetime }
    form.type.editor:
        class: Jasny\FrameworkBundle\Form\Type\EditorType
        tags:
            - { name: form.type, alias: editor }
    form.type.link:
        class: Jasny\FrameworkBundle\Form\Type\LinkType
        tags:
            - { name: form.type, alias: link }
    form.type.phonenumber:
        class: Jasny\FrameworkBundle\Form\Type\PhonenumberType
        tags:
            - { name: form.type, alias: phonenumber }
    form.type.country:
        class: Jasny\FrameworkBundle\Form\Type\CountryType
        tags:
            - { name: form.type, alias: country }
    form.type.file:
        class: Jasny\FrameworkBundle\Form\Type\FileType
        tags:
            - { name: form.type, alias: file }
    form.type.image:
        class: Jasny\FrameworkBundle\Form\Type\ImageType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: image }
