<?php

/*
 * This file is part of the Jasny extension on Symfony.
 *
 * (c) Arnold Daniels <arnold@jasny.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Jasny\ORMBundle;

/**
 * Interface to indicate an entity has an autogenerated reference.
 * 
 * By default the source value is optained by casting the entity to a string.
 * Alternatively implement method `getReferenceSource()` to return the source
 * for the reference. This function can return either a string or an array of
 * strings.
 */
interface AutoReferencing extends Referenceable
{
    /**
     * Set reference.
     * 
     * @param string $value
     */
	public function setReference($value);
}
