parameters:
    jasny_ckeditor.kcfinder.class: Jasny\CKEditorBundle\Services\KCFinder
    jasny_ckeditor.form.type.class: Jasny\CKEditorBundle\Form\Type\CKEditorType
    
services:
    ckeditor.kcfinder:
        class: %jasny_ckeditor.kcfinder.class%
        arguments: ['@service_container', %jasny_ckeditor.upload_dir%]
    form.type.ckeditor:
        class: %jasny_ckeditor.form.type.class%
        tags:
            - { name: form.type, alias: ckeditor }
