<?php

/*
 * This file is part of the Jasny extension on Symfony.
 *
 * (c) Arnold Daniels <arnold@jasny.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Jasny\Bundle\ORMBundle;

/**
 * Interface to indicate an entity has an autogenerated reference.
 */
interface AutoReferencing extends Referenceable
{
    /**
     * Set reference.
     * 
     * @param string $value
     */
	public function setReference($value);
    
    /**
     * Get source values for reference.
     * 
     * @return array
     */
	public function getReferenceSource();
}
