# These Doctrine DQL function should be automatically added when adding the Jasny ORM bundle
# For now please load '@JasnyORMBundle/Resources/config/doctrine.yml' into the configuration

doctrine:
    orm:
        entity_managers:
            default:
                dql:
                    string_functions:
                        distance: Jasny\ORMBundle\Functions\Distance
                        geom:     Jasny\ORMBundle\Functions\Geom
