services:
    form.type.base_form:
        class: Jasny\Bundle\FrameworkBundle\Form\BaseFormType
        tags:
            - { name: form.type, alias: base_form }
    form.type.date:
        class: Jasny\Bundle\FrameworkBundle\Form\Type\DateType
        tags:
            - { name: form.type, alias: date }
    form.type.datetime:
        class: Jasny\Bundle\FrameworkBundle\Form\Type\DateTimeType
        tags:
            - { name: form.type, alias: datetime }
    form.type.editor:
        class: Jasny\Bundle\FrameworkBundle\Form\Type\EditorType
        tags:
            - { name: form.type, alias: editor }
#twig:
#    form:
#        resources:
#            - "JasnyFrameworkBundle:Form:form_layout.html.twig"
