services:
    form.type.date:
        class: Jasny\Bundle\FrameworkBundle\Form\Type\DateType
        tags:
            - { name: form.type, alias: date }
    form.type.datetime:
        class: Jasny\Bundle\FrameworkBundle\Form\Type\DateTimeType
        tags:
            - { name: form.type, alias: datetime }
