services:
    twig.extension.text:
        class: Jasny\Bundle\FrameworkBundle\Twig\TextExtension
        tags:
            - { name: twig.extension }
    twig.extension.pcre:
        class: Jasny\Bundle\FrameworkBundle\Twig\PcreExtension
        tags:
            - { name: twig.extension }
    twig.extension.localdate:
        class: Jasny\Bundle\FrameworkBundle\Twig\LocalDateExtension
        tags:
            - { name: twig.extension }
